# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 429)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 181, 16))
        self.label.setToolTipDuration(2000)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 171, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_background = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_background.setGeometry(QtCore.QRect(250, 20, 113, 21))
        self.lineEdit_background.setObjectName("lineEdit_background")
        self.lineEdit_gear = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_gear.setGeometry(QtCore.QRect(250, 50, 113, 21))
        self.lineEdit_gear.setObjectName("lineEdit_gear")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 171, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 381, 111))
        self.groupBox.setWhatsThis("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_shortcut = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_shortcut.setGeometry(QtCore.QRect(230, 70, 113, 21))
        self.lineEdit_shortcut.setClearButtonEnabled(False)
        self.lineEdit_shortcut.setObjectName("lineEdit_shortcut")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 140, 181, 81))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_reviewer = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_reviewer.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.checkBox_reviewer.setToolTip("")
        self.checkBox_reviewer.setChecked(True)
        self.checkBox_reviewer.setObjectName("checkBox_reviewer")
        self.checkBox_toolbar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_toolbar.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.checkBox_toolbar.setChecked(True)
        self.checkBox_toolbar.setObjectName("checkBox_toolbar")
        self.checkBox_topbottom = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_topbottom.setGeometry(QtCore.QRect(10, 50, 151, 20))
        self.checkBox_topbottom.setChecked(True)
        self.checkBox_topbottom.setObjectName("checkBox_topbottom")
        self.Slider_main = QtWidgets.QSlider(Dialog)
        self.Slider_main.setGeometry(QtCore.QRect(270, 160, 111, 22))
        self.Slider_main.setToolTip("")
        self.Slider_main.setToolTipDuration(-1)
        self.Slider_main.setWhatsThis("")
        self.Slider_main.setMinimum(1)
        self.Slider_main.setMaximum(100)
        self.Slider_main.setPageStep(10)
        self.Slider_main.setProperty("value", 100)
        self.Slider_main.setSliderPosition(100)
        self.Slider_main.setTracking(True)
        self.Slider_main.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_main.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_main.setTickInterval(5)
        self.Slider_main.setObjectName("Slider_main")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(220, 160, 41, 16))
        self.label_5.setToolTip("")
        self.label_5.setToolTipDuration(2000)
        self.label_5.setStatusTip("")
        self.label_5.setWhatsThis("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 190, 51, 16))
        self.label_6.setObjectName("label_6")
        self.Slider_review = QtWidgets.QSlider(Dialog)
        self.Slider_review.setGeometry(QtCore.QRect(270, 190, 111, 22))
        self.Slider_review.setMaximum(100)
        self.Slider_review.setProperty("value", 100)
        self.Slider_review.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_review.setObjectName("Slider_review")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 120, 191, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_attachment = QtWidgets.QComboBox(Dialog)
        self.comboBox_attachment.setGeometry(QtCore.QRect(120, 240, 104, 26))
        self.comboBox_attachment.setObjectName("comboBox_attachment")
        self.comboBox_attachment.addItem("")
        self.comboBox_attachment.addItem("")
        self.comboBox_position = QtWidgets.QComboBox(Dialog)
        self.comboBox_position.setGeometry(QtCore.QRect(120, 270, 104, 26))
        self.comboBox_position.setObjectName("comboBox_position")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.comboBox_position.addItem("")
        self.lineEdit_color_main = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_color_main.setGeometry(QtCore.QRect(90, 360, 81, 21))
        self.lineEdit_color_main.setObjectName("lineEdit_color_main")
        self.lineEdit_color_top = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_color_top.setGeometry(QtCore.QRect(302, 360, 81, 21))
        self.lineEdit_color_top.setObjectName("lineEdit_color_top")
        self.lineEdit_color_bottom = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_color_bottom.setGeometry(QtCore.QRect(302, 390, 81, 21))
        self.lineEdit_color_bottom.setObjectName("lineEdit_color_bottom")
        self.comboBox_size = QtWidgets.QComboBox(Dialog)
        self.comboBox_size.setGeometry(QtCore.QRect(120, 300, 104, 26))
        self.comboBox_size.setObjectName("comboBox_size")
        self.comboBox_size.addItem("")
        self.comboBox_size.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 300, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(240, 290, 81, 16))
        self.label_9.setObjectName("label_9")
        self.scaleBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.scaleBox.setGeometry(QtCore.QRect(310, 290, 68, 24))
        self.scaleBox.setDecimals(1)
        self.scaleBox.setMinimum(0.1)
        self.scaleBox.setProperty("value", 1.0)
        self.scaleBox.setObjectName("scaleBox")
        self.comboBox_repeat = QtWidgets.QComboBox(Dialog)
        self.comboBox_repeat.setGeometry(QtCore.QRect(290, 250, 104, 26))
        self.comboBox_repeat.setObjectName("comboBox_repeat")
        self.comboBox_repeat.addItem("")
        self.comboBox_repeat.addItem("")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(240, 250, 81, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 229, 381, 111))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 340, 381, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(170, 20, 101, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(170, 50, 101, 20))
        self.label_13.setObjectName("label_13")
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_background.raise_()
        self.lineEdit_gear.raise_()
        self.label_3.raise_()
        self.groupBox_2.raise_()
        self.Slider_main.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.Slider_review.raise_()
        self.comboBox_attachment.raise_()
        self.comboBox_position.raise_()
        self.lineEdit_color_main.raise_()
        self.lineEdit_color_top.raise_()
        self.lineEdit_color_bottom.raise_()
        self.comboBox_size.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.scaleBox.raise_()
        self.comboBox_repeat.raise_()
        self.label_10.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p>Full filename of image in the user_files folder (including extension)</p></body></html>"))
        self.label.setText(_translate("Dialog", "Image name for background:"))
        self.label_2.setText(_translate("Dialog", "Image name for gear:"))
        self.label_3.setText(_translate("Dialog", "Keyboard shortcut:"))
        self.checkBox_reviewer.setText(_translate("Dialog", "Reviewer image"))
        self.checkBox_toolbar.setText(_translate("Dialog", "Toolbar image"))
        self.checkBox_topbottom.setText(_translate("Dialog", "Toolbar top/bottom"))
        self.label_5.setText(_translate("Dialog", "Main"))
        self.label_6.setText(_translate("Dialog", "Review"))
        self.groupBox_3.setTitle(_translate("Dialog", "Background opacity"))
        self.comboBox_attachment.setItemText(0, _translate("Dialog", "fixed"))
        self.comboBox_attachment.setItemText(1, _translate("Dialog", "scroll"))
        self.comboBox_position.setCurrentText(_translate("Dialog", "top left"))
        self.comboBox_position.setItemText(0, _translate("Dialog", "top left"))
        self.comboBox_position.setItemText(1, _translate("Dialog", "top center"))
        self.comboBox_position.setItemText(2, _translate("Dialog", "top right"))
        self.comboBox_position.setItemText(3, _translate("Dialog", "right"))
        self.comboBox_position.setItemText(4, _translate("Dialog", "left"))
        self.comboBox_position.setItemText(5, _translate("Dialog", "center"))
        self.comboBox_position.setItemText(6, _translate("Dialog", "bottom left"))
        self.comboBox_position.setItemText(7, _translate("Dialog", "bottom center"))
        self.comboBox_position.setItemText(8, _translate("Dialog", "bottom right"))
        self.comboBox_size.setItemText(0, _translate("Dialog", "cover"))
        self.comboBox_size.setItemText(1, _translate("Dialog", "contain"))
        self.label_4.setText(_translate("Dialog", "Attachment:"))
        self.label_7.setText(_translate("Dialog", "Position:"))
        self.label_8.setText(_translate("Dialog", "Size:"))
        self.label_9.setText(_translate("Dialog", "Scale:"))
        self.comboBox_repeat.setItemText(0, _translate("Dialog", "no-repeat"))
        self.comboBox_repeat.setItemText(1, _translate("Dialog", "repeat"))
        self.label_10.setText(_translate("Dialog", "Repeat:"))
        self.groupBox_5.setTitle(_translate("Dialog", "Background color"))
        self.label_11.setText(_translate("Dialog", "Main:"))
        self.label_12.setText(_translate("Dialog", "Top toolbar:"))
        self.label_13.setText(_translate("Dialog", "Bottom toolbar:"))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
'''
